### ISSUE TITLE
Mk4-1 "Amalthea" Command Module - Pilot and Co-pilot RPM screens not visible

### ISSUE THREAD

**Issue by themaster402** [post-kerbin-mining-corporation/NearFutureSpacecraft#140]
Occurs in 1.9.1 in an install with NFS, RPM, and ASET, no other part/gameplay mods. Tried to scout where there may have been an error in loading but was unable to discover it myself.
![KSP_x64_KYUg7PHTl1](https://user-images.githubusercontent.com/5889962/84600389-8b577400-ae81-11ea-892e-403bdbcd178b.png)

**Comment by ChrisAdderley** [comment]
RPM is barely supported and the config author left a long time ago.
