### ISSUE TITLE
Mk1-25B heatshiel diamater lower than bottom diameter

### ISSUE THREAD

**Issue by Gordon-Dry** [post-kerbin-mining-corporation/NearFutureSpacecraft#163]
Is this pod not intended to be used for atmospheric reentries?
With a heatshield that has a smaller diameter then the pod it will overheat... perhaps it works on stock, but on JNSQ 10x it just does not work.

**Comment by ChrisAdderley** [comment]
Mod is not designed for JNSQ 10x.
